# Generated by Django 3.2.9 on 2021-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='origin',
            field=models.DateField(),
        ),
    ]
